!> Last Modified : Sat Feb 25 16:08:50 2023


Module MDU_exact_riemann_slover


	real*8,private:: G1 ,G2,G3,G4,G5,G6,G7,G8
	real*8,private:: UL,PL ,CL, DL
	real*8,private:: UR,PR ,CR, DR
	real*8,private :: G
	integer,private :: n
	real*8,private  :: d,e,p,u,c,h,e1,v,w,a1,a2,a


contains   


	subroutine exact_riemann_problem_pstar_ustar(r1,u1,p1,r2,u2,p2,gamma,pstar,ustar)
		implicit real*8 (A-H,M,O-Z)
		real*8,intent(in)  :: r1,u1,p1,r2,u2,p2,gamma
		real*8,intent(out) :: pstar,ustar

		DL=r1
		UL=u1
		PL=p1

		DR=r2
		UR=u2
		PR=p2

		G = gamma
		G1 = (G - 1.0)/(2.0*G)
		G2 = (G + 1.0)/(2.0*G)
		G3 = 2.0*G/(G - 1.0)
		G4 = 2.0/(G - 1.0)
		G5 = 2.0/(G + 1.0)
		G6 = (G - 1.0)/(G + 1.0)
		G7 = (G - 1.0)/2.0
		G8 = G - 1.0

		CL = Dsqrt(max(0.0,G*PL/DL))
		CR = Dsqrt(max(0.0,G*PR/DR))

		!
		!   The pressure positivity condition is tested for
		!
		IF(G4*(CL+CR).LE.(UR-UL))THEN
			!
			!   The initial data is such that vacuum is generated.
			!   Program stopped.
			!
			!WRITE(6,*)
			!WRITE(6,*)'***Vacuum is generated by data***'
			!WRITE(6,*)'***Program stopped***'
			!WRITE(6,*)
			!
			CVar = 0.5*(CVARL+CVARR)
			!STOP
			return
		ENDIF
		!
		!    Exact solution for pressure and velocity in star
		!    region is found
		!
		!         
		CALL STARPU(PM,UM)

		pstar = PM
		ustar = um
		!
		!    Complete self similar solution at dx/dt = S is found
		!
		! CALL SAMPLE( PM, UM, s, D, U, P)

		! PVar(1) = D
		! PVar(2) = U
		! PVar(n) = P
		! if(S.LE.UM)then
		! PVar(3:n-1) = PVarL(3:n-1)
		! else
		! PVar(3:n-1) = PVarR(3:n-1)
		! endif

		! call PVarToCVar(PVar,CVar)

	ENDsubroutine exact_riemann_problem_pstar_ustar   


	!*****************************************************
	!   Purpose: to compute the solution for pressure and
	!           velocity in the Star Region
	!*****************************************************
	SUBROUTINE STARPU(P, U )
		implicit real*8 (A-H,O-Z)
		DATA TOLPRE, NRITER/1.0E-6, 20/
		!
		CALL GUESSP(PSTART)
		!
		POLD  = PSTART
		UDIFF = UR - UL
		!
		DO 10 I = 1, NRITER
		!
		CALL PREFUN(FL, FLD, POLD, DL, PL, CL)
		CALL PREFUN(FR, FRD, POLD, DR, PR, CR)
		P     = POLD - (FL + FR + UDIFF)/(FLD + FRD)
		CHANGE = 2.0*ABS((P - POLD)/(P + POLD))
		IF(CHANGE.LE.TOLPRE)GOTO 20
		IF(P.LT.0.0)P = TOLPRE
		POLD  = P
		!
		10   CONTINUE
		20   CONTINUE
		!
		!    Compute velocity in Star Region
		!
		U = 0.5*(UL + UR + FR - FL)
	ENDSUBROUTINE STARPU
	!*********************************************************
	!
	!    Purpose: to provide a guessed value for pressure
	!           PM in the Star Region. The choice is made
	!           according to adaptive Riemann solver using
	!           the PVRS, TRRS and TSRS approximate
	!           Riemann solvers. See Sect. 9.5 of Chapt. 9
	!           of Ref. 1
	!*********************************************************
	SUBROUTINE GUESSP(PM)
		implicit real*8 (A-H,O-Z)
		!
		!
		QUSER = 2.0
		!
		!    Compute guess pressure from PVRS Riemann solver
		!
		CUP  = 0.25*(DL + DR)*(CL + CR)
		PPV  = 0.5*(PL + PR) + 0.5*(UL - UR)*CUP
		PPV  = MAX(0.0, PPV)
		PMIN = MIN(PL,  PR)
		PMAX = MAX(PL,  PR)
		QMAX = PMAX/PMIN
		!
		IF(QMAX.LE.QUSER.AND. (PMIN.LE.PPV.AND.PPV.LE.PMAX))THEN
			!
			!      Select PVRS Riemann solver
			!
			PM = PPV
		ELSE
			IF(PPV.LT.PMIN)THEN
				!
				!         Select Two-Rarefaction Riemann solver
				!
				PQ  = (PL/PR)**G1
				UM  = (PQ*UL/CL + UR/CR + G4*(PQ - 1.0))/(PQ/CL + 1.0/CR)
				PTL = 1.0 + G7*(UL - UM)/CL
				PTR = 1.0 + G7*(UM - UR)/CR
				PM  = 0.5*(PL*PTL**G3 + PR*PTR**G3)
			ELSE
				!
				!         Select Two-Shock Riemann solver with
				!         PVRS as estimate
				!
				GEL = Dsqrt(max(0.0,(G5/DL)/(G6*PL + PPV)))
				GER = Dsqrt(max(0.0,(G5/DR)/(G6*PR + PPV)))
				PM  = (GEL*PL + GER*PR - (UR - UL))/(GEL + GER)
			ENDIF
		ENDIF
		!
	END SUBROUTINE GUESSP
	!***********************************************************
	!
	!   Purpose: to evaluate the pressure functions
	!          FL and FR in exact Riemann solver
	!          and their first derivatives
	!
	!***********************************************************
	SUBROUTINE PREFUN( F, FD, P, DK, PK, CK )
		implicit real*8 (A-H,O-Z)
		!
		!
		IF(P.LE.PK)THEN
			!
			!      Rarefaction wave
			!
			PRATIO = P/PK
			F   = G4*CK*(PRATIO**G1 - 1.0)
			FD   = (1.0/(DK*CK))*PRATIO**(-G2)
		ELSE
			!
			!      Shock wave
			!
			AK  = G5/DK
			BK  = G6*PK
			QRT = DSQRT(dmax1(0.d0,AK/(BK + P)))
			F   = (P - PK)*QRT
			FD  = (1.0 - 0.5*(P - PK)/(BK + P))*QRT
		ENDIF
		!
	ENDSUBROUTINE PREFUN
	!***********************************************************
	!
	!    Purpose: to sample the solution throughout the wave
	!           pattern. Pressure PM and velocity UM in the
	!           Star Region are known. Sampling is performed
	!           in terms of the 'speed' S = X/T. Sampled
	!           values are D, U, P
	!***********************************************************
	!
	!Input variables : PM, UM,  
	!Output variables: d,u,p,z
	SUBROUTINE SAMPLE(PM, UM, s, D, U, P)
		implicit real*8 (A-H,O-Z)
		!
		!   sampling of massfraction z
		!
		!   Sampling of state variables: d,u,p
		!
		IF(S.LE.UM)THEN
			!
			!      Sampling point lies to the left of the contact
			!      discontinuity
			!
			IF(PM.LE.PL)THEN
				!
				!         Left rarefaction
				!
				SHL = UL - CL
				!
				IF(S.LE.SHL)THEN

					!
					!           Sampled point is left data state
					!
					D = DL
					U = UL
					P = PL
				ELSE
					CML = CL*(PM/PL)**G1
					STL = UM - CML
					!
					IF(S.GT.STL)THEN
						!
						!             Sampled point is Star Left state
						!
						D = DL*(PM/PL)**(1.0/G)
						U = UM
						P = PM
					ELSE
						!
						!             Sampled point is inside left fan
						!
						U = G5*(CL + G7*UL + S)
						C = G5*(CL + G7*(UL - S))
						D = DL*(C/CL)**G4
						P = PL*(C/CL)**G3
					ENDIF
				ENDIF
			ELSE
				!
				!         Left shock
				!
				PML = PM/PL
				SL  = UL - CL*DSQRT(Dmax1(0.0, G2*PML + G1))
				!
				IF(S.LE.SL)THEN
					!
					!           Sampled point is left data state
					!
					D = DL
					U = UL
					P = PL
					!
				ELSE
					!
					!           Sampled point is Star Left state
					!
					D = DL*(PML + G6)/(PML*G6 + 1.0)
					U = UM
					P = PM
				ENDIF
			ENDIF
		ELSE
			!
			!      Sampling point lies to the right of the contact
			!      discontinuity
			!
			IF(PM.GT.PR)THEN
				!
				!         Right shock
				!
				PMR = PM/PR
				SR  = UR + CR*DSQRT(Dmax1(0.0,G2*PMR + G1))
				!
				IF(S.GE.SR)THEN
					!
					!           Sampled point is right data state
					!
					D = DR
					U = UR
					P = PR
				ELSE
					!
					!           Sampled point is Star Right state
					!
					D = DR*(PMR + G6)/(PMR*G6 + 1.0)
					U = UM
					P = PM
				ENDIF
			ELSE
				!
				!         Right rarefaction
				!
				SHR = UR + CR
				!
				IF(S.GE.SHR)THEN
					!
					!           Sampled point is right data state
					!
					D = DR
					U = UR
					P = PR
				ELSE
					CMR = CR*(PM/PR)**G1
					STR = UM + CMR
					!
					IF(S.LE.STR)THEN
						!
						!             Sampled point is Star Right state
						!
						D = DR*(PM/PR)**(1.0/G)
						U = UM
						P = PM
					ELSE
						!
						!             Sampled point is inside left fan
						!
						U = G5*(-CR + G7*UR + S)
						C = G5*(CR - G7*(UR - S))
						D = DR*(C/CR)**G4
						P = PR*(C/CR)**G3
					ENDIF
				ENDIF
			ENDIF
		ENDIF
		!
	END SUBROUTINE SAMPLE


	!******************************************
	!subroutine RPSolver_Euler( CVarL,CVarR,s,CVar )
	!   implicit real*8 (A-H,M,O-Z)
	!   real*8,dimension(:),intent(in):: CVarL,CVarR
	!   real*8,dimension(:),intent(inout)::CVar
	!   real*8,intent(in):: s
	!
	!   real*8,dimension(size(CVar)) :: PVarL,PVarR,PVar
	!
	!   call CVarToPVar(CVarL,PVarL)
	!   call CVarToPVar(CVarR,PVarR)
	!   n = size(CVar)
	!
	!   DL=PVarL(1)
	!   UL=PVarL(2)
	!   PL=PVarL(n)
	!         
	!
	!   DR=PVarR(1)
	!   UR=PVarR(2)
	!   PR=PVarR(n)
	!   
	!   G1 = (G - 1.0)/(2.0*G)
	!   G2 = (G + 1.0)/(2.0*G)
	!   G3 = 2.0*G/(G - 1.0)
	!   G4 = 2.0/(G - 1.0)
	!   G5 = 2.0/(G + 1.0)
	!   G6 = (G - 1.0)/(G + 1.0)
	!   G7 = (G - 1.0)/2.0
	!   G8 = G - 1.0
	!
	!   CL = Dsqrt(max(0.0,G*PL/DL))
	!   CR = Dsqrt(max(0.0,G*PR/DR))
	!
	!!
	!!   The pressure positivity condition is tested for
	!!
	!   IF(G4*(CL+CR).LE.(UR-UL))THEN
	!!
	!!   The initial data is such that vacuum is generated.
	!!   Program stopped.
	!!
	!   !WRITE(6,*)
	!   !WRITE(6,*)'***Vacuum is generated by data***'
	!   !WRITE(6,*)'***Program stopped***'
	!   !WRITE(6,*)
	!!
	!   CVar = 0.5*(CVARL+CVARR)
	!   !STOP
	!   return
	!   ENDIF
	!!
	!!    Exact solution for pressure and velocity in star
	!!    region is found
	!!
	!!         
	!   CALL STARPU(PM,UM)
	!!
	!!    Complete self similar solution at dx/dt = S is found
	!!
	!   CALL SAMPLE( PM, UM, s, D, U, P)
	!
	!   PVar(1) = D
	!   PVar(2) = U
	!   PVar(n) = P
	!   if(S.LE.UM)then
	!      PVar(3:n-1) = PVarL(3:n-1)
	!   else
	!      PVar(3:n-1) = PVarR(3:n-1)
	!   endif
	!
	!   call PVarToCVar(PVar,CVar)
	!
	!END subroutine RPSolver_Euler


End Module MDU_exact_riemann_slover
